### ISSUE TITLE
Installation instructions clarification

### ISSUE THREAD

**Issue by jopineda** [cdarby/samovar#2]
Hi,

I am trying to install samovar and from the instructions on the README, I'm a bit unsure about how to do so. Can you please provide more clarification as to where I would need to "change the INSTALLDIR, PYTHONCMD, and PYPYCMD variables"?

Thanks so much for your time!
Best,
Joanna

**Comment by cdarby** [comment]
Hi Joanna - I had neglected to update the repo with the wrapper script, `./samovar` which has the environment variables you'll change. The latest commit adds this file. Thanks for bringing this to our attention!
